### ISSUE TITLE
getting mastodon-backup packaged (for Linux)

### ISSUE THREAD

**Issue by IzzySoft** [kensanata/mastodon-archive#80]
As discussed in #78 we will go about packaging mastodon-backup for Linux distributions – a task I've adopted. Attached you'll find the first packages to test (I had to rename the files to `*.zip` or Github won't let me attach them – so simply remove the `.zip` suffix to get working packages):

* [mastodon-archive_1.4.3-izzy1_all.deb.zip](https://github.com/kensanata/mastodon-archive/files/10097004/mastodon-archive_1.4.3-izzy1_all.deb.zip)
* [mastodon-archive-1.4.3-izzy1.noarch.rpm.zip](https://github.com/kensanata/mastodon-archive/files/10097005/mastodon-archive-1.4.3-izzy1.noarch.rpm.zip)

(previous versions in the "historical comment" below)

### Known culprits
mostly affect one of the 3 dependencies, `python3-mastodon` (resp. `python3-Mastodon` for the RPM):

* Ubuntu 20.04 and derivates ship an outdated v1.5.0 (bookmarks not working); 22.04 will have v1.5.1
* Debian Buster ships an even more outdated v1.3.1 (no ideas what might be broken here); Bullseye & Sid ship the latest v1.5.1 which is fine
* for RPM based distributions, I only found `python3-Mastodon` mentioned with Fedora (Fedora 35+ ships v1.5.1)

As for v1.5.0, @kensanata already implemented a "catch" so if you run `mastodon-backup` with `--mentions` it will not crash but only skip bookmarks, displaying a warning. We did not test against v1.3.1.

### Open todos
* [x] catch the bookmark error with `--mention` (fix already included with the initial packages)
* [x] provide a script in `contrib/` to "manually" update `python3-mastodon` to v1.5.1 => #81 
* [x] establish a Readme in `contrib/` => #82 
* [x] **Lots of testing and Feedback** – that's what the files are attached for here. Whenever noticable fixes/updates made it into the `main` branch, I'll try to create and provide new packages ASAP.
* [x] amending a check-list to track testing progress: which distributions in which versions are covered, are there any culprits, are there (easy) work-arounds for those culprits, can they be solved from our (@kensanata's and my) side and if so, are they solved … (note: all feedback received was positive, no culprits apart from outdated `Mastodon.py` which is covered by `contrib/upgrade_python-mastodon.sh`)
* update documentation:
  * [x] checking/amending `RELEASE.md`  whether additional steps need to be pinned down for the regular release process (then including packaging)
  * [x] updating `README.md` with the new options concerning installation instructions, see #90 (and while on it: check all links. For example, [forget is no longer available](https://forget.codl.fr/notice.html))

Testing is where **YOU** (the users running a Linux distro) come in. Please help us getting this mature! As pointed out, the latest packages for testing are attached to this post. Should newer become available, you'll find them here (and a comment of them being available – so you can subscribe this issue for updates).

PS: Once the packages are declared to be "mature", I'll add (and maintain) them via [my repo](https://apt.izzysoft.de/) which you can easily add for `apt` as well as `yum` (descriptions there).

**Comment by IzzySoft** [comment]
Just for history (newest first):

### DEBs
[mastodon-backup_1.4.2-izzy2_all.deb.zip](https://github.com/kensanata/mastodon-backup/files/9912415/mastodon-backup_1.4.2-izzy2_all.deb.zip)
* [mastodon-backup_1.4.2-izzy1_all.deb.zip](https://github.com/kensanata/mastodon-backup/files/9899639/mastodon-backup_1.4.2-izzy1_all.deb.zip): package for Debian, Ubuntu and derivates (rename to `mastodon-backup_1.4.2-izzy1_all.deb`)


### RPMs
* [mastodon-backup-1.4.2-izzy2.noarch.rpm.zip](https://github.com/kensanata/mastodon-backup/files/9912420/mastodon-backup-1.4.2-izzy2.noarch.rpm.zip)
* [mastodon-backup-1.4.2-izzy1.noarch.rpm.zip](https://github.com/kensanata/mastodon-backup/files/9899647/mastodon-backup-1.4.2-izzy1.noarch.rpm.zip): RPM for Redhat, Fedora & Co (rename to `mastodon-backup-1.4.2-izzy1.noarch.rpm`)

**Comment by IzzySoft** [comment]
```
$ git pull upstream main 
From github.com:kensanata/mastodon-backup
 * branch            main       -> FETCH_HEAD
Already up to date.
```

At least the git client has no issues (and as you can see, I did not rename/replace the `git remote` yet – which could be done e.g. using `git remote set-url [--push] <name> <newurl> [<oldurl>]`).

**Comment by IzzySoft** [comment]
@kensanata throughout the docs and in `media.py` (line 77), 'mastodon-backup' needs to be replaced by 'mastodon-archive' as well. Will you, or shall I provide another PR?

**Comment by plettich** [comment]
> +1 WFM, AFAICT, debian sid

Same here, Fedora 36

**Comment by IzzySoft** [comment]
Thanks! That already makes 2 positive reports for each of the two (one 1+1 received at the Fedi), and no negative :partying_face:

@kensanata up to you to decide if you first want to tag v1.4.3 before we let the packages fly then.

**Comment by IzzySoft** [comment]
@kensanata seems the hint on "outdated `Mastodon.py` could need a pointer to details (e.g. `contrib/README.md#upgrade_python-mastodonsh-by-izzy` or to the related issue). From a [report on Ubuntu 20.04](https://nerd.megahuge.com/@bashley/109343764459576866):

> when I supply `--no-stopping`, skips benchmarks due to Mastodon.py version

I've asked, and the author of the toot wrote outdated `Mastodon.py` was reported …

> but no discussion or solution link supplied. I looked up the extended reason (20.04) and discussions of solution from the git discussion

**Comment by kensanata** [comment]
> @kensanata throughout the docs and in `media.py` (line 77) plus `setup.py` (line 14), 'mastodon-backup' needs to be replaced by 'mastodon-archive' as well. Will you, or shall I provide another PR?

I will do a `git grep` and see what I can do.

**Comment by kensanata** [comment]
> @kensanata throughout the docs and in `media.py` (line 77) plus `setup.py` (line 14), 'mastodon-backup' needs to be replaced by 'mastodon-archive' as well. Will you, or shall I provide another PR?

Thanks for doing this!

**Comment by kensanata** [comment]
> > but no discussion or solution link supplied. I looked up the extended reason (20.04) and discussions of solution from the git discussion
> 
> **Edit:** author reported `upgrade_python-mastodon.sh` fixed the issue for them \o/

Hm. Not sure what to do. I would like the message to be independent from being online, and therefore requiring users to follow a link. We should just dump screens full of text from the commands: explain the problem, tell them about the location of a script that helps them upgrade their installation.

**Comment by IzzySoft** [comment]
> I will do a git grep and see what I can do.

You've already merged the PR including that :smile:

> Thanks for doing this!

Gladly! I'm eager to get those packages deployed :zany_face:

> We should just dump screens full of text from the commands

Well, they either downloaded from here and installed via `setup.py`, or via PyPi, or via the packages. In any case, shouldn't they have received the `contrib/` contents along then? Why not simply point out that there's a script for that in there, dettails included with it? Just thinking aloud… Like: "For details, see the README.md in the contrib/ directory describing upgrade_python-mastodon.sh."

**Comment by kensanata** [comment]
I'm not sure. At least where I am concerned when I install packages via a package manager I usually have no idea that more files are installed and where they are installed. So yeah, if the message at least pointed to the actual fully qualified file, then that'd be great.

**Comment by IzzySoft** [comment]
If the file name is mentioned, you can always use `locate` (or at least `find` if you didn't install `locate`). With Linux packages, there's always the docs in `/usr/share/doc/<packageName>`. No idea however what PIP would do if you fetch from PyPi. Would it pull the docs along at all? Do you need to declare them in `setup.py` for that? I have no idea, so I better leave the decision to you. Was just transporting the report – and after all, at least that user found the solution easy enough without additional hints.

**Comment by kensanata** [comment]
Something like this?

```diff
@@ -154,6 +154,9 @@ def archive(args):
     except AttributeError as e:
         bookmarks = []
         print("Skipping bookmarks since your Mastodon.py library is too old!")
+        print("You might have a file called upgrade_python-mastodon.sh on your system.")
+        print("Find it using 'locate upgrade_python-mastodon.sh' and then run it to attempt")
+        print("an upgrade in-place: 'bash /path/to/upgrade_python-mastodon.sh'")
 
     if not with_mentions:
         print("Skipping mentions")
```

**Comment by IzzySoft** [comment]
Yes! :smiley: Minor adjustment suggested: "Find it **e.g.** using 'locate…'" (`locate` is not pre-installed, folks might have to use `find / -name upgrade_python-mastodon.sh`).

**Comment by kensanata** [comment]
Done → fe31886

**Comment by IzzySoft** [comment]
Final packages are attached now as well, in addition to being available in my repo. Ready to finalize!

**Comment by IzzySoft** [comment]
I hereby declare this issue solved :partying_face:

* Thanks to all testers!!!
* Thanks to @kensanata for all the patience along the way!
* Happy installing, all ya Linux users on Debian and RPM based systems! Should there be troubles with those packages, please report (and @kensanata will assign those issues to me then, please)
